
- block:
    - name: Install webserver packages
      package: name={{ item }} state=present
      with_items:
        - "{{ webserver_package_name }}"
        - "{{ wsgi_package_name }}"
      environment: "{{ proxy_env }}"

    - name: enable apache2 required modules
      apache2_module: state=present name={{ item }}
      loop: "{{ apache2_required_modules }}"

    - set_fact: api_server_name="{{ ansible_hostname }}"          #  this only works for importer = backend

    - name: create apache certificates
      include_role:
        name: openssl-cert
      vars:
        openssl_cert_path: /etc/apache2/ssl
        openssl_user: root
        openssl_cert_mode: "{{ api_tls_certificate.mode }}"
        openssl_force_renew: "{{ api_tls_certificate.force_renew }}"
        openssl_cert_src: "{{ api_tls_certificate.cert_src }}"
        openssl_cert_content: "{{ api_tls_certificate.cert_content }}"
        openssl_private_key_src: "{{ api_tls_certificate.key_src }}"
        openssl_private_key_content: "{{ api_tls_certificate.key_content }}"
        openssl_chain_src: "{{ api_tls_certificate.chain_src }}"
        openssl_chain_content: "{{ api_tls_certificate.chain_content }}"
        openssl_trust_ca_file: "{{ api_tls_certificate.trust_ca_installed_path if api_tls_certificate.trust_ca_src | length > 0 or api_tls_certificate.trust_ca_content | length > 0 else internal_ca_trust_cert }}"
        openssl_private_key: "{{ openssl_cert_path }}/server.key"
        openssl_csr: "{{ openssl_cert_path }}/server.csr"
        openssl_country: DE
        openssl_state: Hessen
        openssl_location: Frankfurt
        openssl_organization: Cactus eSecurity
        openssl_email_address: "fworch@cactus.de"
        openssl_common_name: "{{ api_network_listening_ip_address }}"
        openssl_subject_alt_names:
          - "{{ 'IP:' ~ api_network_listening_ip_address if api_network_listening_ip_address is match('^\\d{1,3}(\\.\\d{1,3}){3}$') else 'DNS:' ~ api_network_listening_ip_address }}"
        openssl_cert: "{{ openssl_cert_path }}/server.crt"
  
    - name: enable apache modules proxy proxy_http ssl rewrite proxy_wstunnel
      apache2_module: state=present name={{ item }}
      loop: "{{ apache2_required_modules }}"

    - name: copy api httpd config file to api target
      template:
        src: "httpd.conf.j2"
        dest: "{{ http_conf_dir }}/{{ product_name }}-api.conf"
        owner: root
        group: root

    - name: enable {{ product_name }} web site
      command: "a2ensite {{ product_name }}-api"

    - name: add port to apache
      lineinfile:
        path: "/etc/apache2/ports.conf"
        line: "    Listen {{ api_web_port }}"
        insertafter: "<IfModule ssl_module>"

    - name: restart apache
      service:
       name: "{{ webserver_package_name }}"
       state: restarted     

  become: true
  environment: "{{ proxy_env }}"
