
- block:
    - name: Install webserver packages
      package: name={{ item }} state=present
      with_items:
        - "{{ webserver_package_name }}"
        - "{{ wsgi_package_name }}"
      environment: "{{ proxy_env }}"

    - name: copy mw httpd config file to mw target
      template:
        src: "httpd.conf"
        dest: "{{ http_conf_dir }}/{{ product_name }}-mw.conf"
        owner: root
        group: root

    - name: enable apache modules proxy proxy_http ssl
      apache2_module: 
        state: present 
        name: "{{ item }}"
      loop: "{{ apache2_required_modules }}"

    - name: create apache certificates
      include_role:
        name: openssl-cert
      vars:
        openssl_cert_path: /etc/apache2/ssl
        openssl_user: root
        openssl_cert_mode: "{{ middleware_tls_certificate.mode }}"
        openssl_force_renew: "{{ middleware_tls_certificate.force_renew }}"
        openssl_cert_src: "{{ middleware_tls_certificate.cert_src }}"
        openssl_cert_content: "{{ middleware_tls_certificate.cert_content }}"
        openssl_private_key_src: "{{ middleware_tls_certificate.key_src }}"
        openssl_private_key_content: "{{ middleware_tls_certificate.key_content }}"
        openssl_chain_src: "{{ middleware_tls_certificate.chain_src }}"
        openssl_chain_content: "{{ middleware_tls_certificate.chain_content }}"
        openssl_trust_ca_file: "{{ middleware_tls_certificate.trust_ca_installed_path if middleware_tls_certificate.trust_ca_src | length > 0 or middleware_tls_certificate.trust_ca_content | length > 0 else internal_ca_trust_cert }}"
        openssl_private_key: "{{ openssl_cert_path }}/server.key"
        openssl_csr: "{{ openssl_cert_path }}/server.csr"
        openssl_country: DE
        openssl_state: Hessen
        openssl_location: Frankfurt
        openssl_organization: Cactus eSecurity
        openssl_email_address: "fworch@cactus.de"
        openssl_common_name: "{{ middleware_hostname }}"
        openssl_subject_alt_names:
          - "DNS:localhost"
          - "IP:127.0.0.1"
          - "{{ 'IP:' ~ middleware_hostname if middleware_hostname is match('^\\d{1,3}(\\.\\d{1,3}){3}$') else 'DNS:' ~ middleware_hostname }}"
        openssl_cert: "{{ openssl_cert_path }}/server.crt"

    - name: enable {{ product_name }} middleware apache site
      command: "a2ensite {{ product_name }}-mw"
      register: testoutput

    - name: add mw port to apache
      lineinfile:
        path: "/etc/apache2/ports.conf"
        line: "Listen {{ middleware_web_listener_port }}"
        insertafter: "<IfModule ssl_module>"

    - name: restart apache
      service:
       name: "{{ webserver_package_name }}"
       state: restarted

  become: true
  environment: "{{ proxy_env }}"
