
- block:
    - name: Install webserver packages
      package: name={{ item }} state=present
      loop:
        - "{{ webserver_package_name }}"
        - "{{ wsgi_package_name }}"
      environment: "{{ proxy_env }}"

    - name: enable required apache modules
      apache2_module: state=present name={{ item }}
      loop: "{{ apache2_required_modules }}"

    - name: create apache certificates
      include_role:
        name: openssl-cert
      vars:
        openssl_cert_path: /etc/apache2/ssl
        openssl_user: root
        openssl_cert_mode: "{{ ui_tls_certificate.mode }}"
        openssl_force_renew: "{{ ui_tls_certificate.force_renew }}"
        openssl_cert_src: "{{ ui_tls_certificate.cert_src }}"
        openssl_cert_content: "{{ ui_tls_certificate.cert_content }}"
        openssl_private_key_src: "{{ ui_tls_certificate.key_src }}"
        openssl_private_key_content: "{{ ui_tls_certificate.key_content }}"
        openssl_chain_src: "{{ ui_tls_certificate.chain_src }}"
        openssl_chain_content: "{{ ui_tls_certificate.chain_content }}"
        openssl_trust_ca_file: "{{ ui_tls_certificate.trust_ca_installed_path if ui_tls_certificate.trust_ca_src | length > 0 or ui_tls_certificate.trust_ca_content | length > 0 else internal_ca_trust_cert }}"
        openssl_private_key: "{{ openssl_cert_path }}/server.key"
        openssl_csr: "{{ openssl_cert_path }}/server.csr"
        openssl_country: DE
        openssl_state: Hessen
        openssl_location: Frankfurt
        openssl_organization: Cactus eSecurity
        openssl_email_address: "fworch@cactus.de"
        openssl_common_name: "{{ ui_hostname }}"
        openssl_subject_alt_names:
          - "{{ 'IP:' ~ ui_hostname if ui_hostname is match('^\\d{1,3}(\\.\\d{1,3}){3}$') else 'DNS:' ~ ui_hostname }}"
        openssl_cert: "{{ openssl_cert_path }}/server.crt"

    - name: copy ui httpd config file to ui target
      template:
        src: "httpd.conf"
        dest: "{{ http_conf_dir }}/{{ product_name }}-ui.conf"
        owner: root
        group: root

    - name: disable apache2 default web site
      command: "a2dissite 000-default"
      ignore_errors: true

    - name: enable {{ product_name }} web site
      command: "a2ensite {{ product_name }}-ui"
      register: testoutput

    - name: test
      debug:
        var: testoutput

    # # currently only necessary here if we are running on the same machine as API
    # - name: increase apache timeout to {{ apache_timeout }} seconds
    #   lineinfile:
    #     path: /etc/apache2/apache2.conf
    #     line: "Timeout {{ apache_timeout }}"

    - name: restart apache
      service:
       name: "{{ webserver_package_name }}"
       state: restarted     

  become: true
  environment: "{{ proxy_env }}"
